Migrate IndieAuth to full authorization_code grant
snarfed/oauth-dropins pull request #284
Opened 2023-01-30 19:55 UTC by jamietanna

A number of IndieAuth servers do not support the IndieAuth-only
[Profile URL Response], so to widen our support for IndieAuth servers we
can migrate to a full authorization_code token grant.

[Profile URL Response]: https://indieauth.spec.indieweb.org/#profile-url-response

2023-01-30 23:10 UTC, snarfed commented
Thank you for starting this! I'll defer to you and @aaronpk et al on whether it's the right idea, you all know more than me, but if you all say go for it, I'm in. The main changes we'd want here in that case are to bring back the authorization endpoint support, for backcompat, and unify `discover_authorization_endpoint` and `discover_token_endpoint`.

2023-01-30 23:13 UTC, snarfed commented
fwiw I tried it against @dshanske's WordPress plugin just now, with a minor bug fix I'll push in a sec, and it died with this error from the plugin:

```json
{
  "error": "parameter_absent",
  "error_description": "Bearer Token Not Supplied or Server Misconfigured to Not Pass Token. Run diagnostic script in WordPress Admin\n\t\t\t\tIndieAuth Settings Page"
}
```

@dshanske does the plugin not yet support the token endpoint flow?

2023-01-30 23:40 UTC, dshanske commented
I'm almost certain I did implement both. Let me check the code

2023-02-02 21:52 UTC, jamietanna commented
Thanks, sorted the backcompat + some tweaks with the setup - should be good to try again now @snarfed

2023-02-03 03:24 UTC, snarfed requested changes
Thank you for the backcompat! Tested against WordPress (my site), works great.

I left a couple comments for duplicated code that should be unified, but otherwise looks great, I'll happily merge once those are done.

2023-02-03 03:24 UTC, snarfed commented on oauth_dropins/indieauth.py
> +      if validate_resp.status_code // 100 == 2:
looks like this onward is the same in both methods, mind pulling it out to the bottom so it's unified?

2023-02-03 03:24 UTC, snarfed commented on oauth_dropins/indieauth.py
> +def discover_token_endpoint(me, resp=None):
this is the same as `discover_authorization_endpoint` except for the rel value, could you unify them?

2023-02-04 10:36 UTC, jamietanna commented
I prefer the "rule of three" for duplication, but happy to have amended :+1:

2023-02-04 19:05 UTC, snarfed commented
> I prefer the "rule of three" for duplication, but happy to have amended 👍

Definitely understood! I'm partial to that too pretty often. Thanks for indulging me here. 😁

2023-02-04 19:06 UTC, snarfed approved these changes
Looks great, thank you! Merging and deploying now, both this app and Bridgy Fed.

2023-02-04 19:06 UTC, merged

2023-02-04 19:42 UTC, snarfed commented
Getting this stack trace on Bridgy Fed when I use this to unfollow someone, IndieAuthing against my site, WordPress 6.1.1 with IndieAuth plugin 4.2.1. Reverting for now until we can debug.

Oddly I'm not seeing this on https://oauth-dropins.appspot.com/ , it's working fine against my site with this change. 🤔 

```
Traceback (most recent call last):
...
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/indieauth.py", line 223, in dispatch_request
    return self.finish(indie_auth, state=state)
  File "/workspace/follow.py", line 202, in finish
    follower = Follower.get_by_id(state)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/ndb/_options.py", line 102, in wrapper
    return wrapped(*pass_args, **kwargs)
...
    raise TypeError(_INVALID_ID_TYPE.format(id_))
TypeError: Key ID must be a string or a number; received {'code_verifier': '...', 'me': 'http://snarfed.org', 'state': 'https://blackrock.city/users/spolsky snarfed.org', 'token_endpoint': 'https://snarfed.org/wp-json/indieauth/1.0/token'}
```

2023-02-04 19:43 UTC, snarfed commented
Tracked in https://console.cloud.google.com/errors/detail/CP2i-vS2ivTshgE;time=P30D?project=bridgy-federated (for myself)

2023-02-04 19:54 UTC, jamietanna commented
Hmm, any idea which key is null that its trying to index into the list? Not one I saw when testing locally with oauth-dropins

2023-02-04 20:58 UTC, snarfed commented
Ah, I see it. When we call `finish` here:

https://github.com/snarfed/oauth-dropins/blob/972d4739233e629cfba6c081a846b558634233bf/oauth_dropins/indieauth.py#L223

...we're supposed to pass the user's `state`, the one they originally passed into `redirect_url`. We did that before with this:

https://github.com/snarfed/oauth-dropins/blob/85c42ef6801b5083e0b9720e3a9b72c9245e8737/oauth_dropins/indieauth.py#L163

...but that line got moved into an `else` in this PR, so it only runs for authorization endpoints, not token endpoints.

https://github.com/snarfed/oauth-dropins/blob/972d4739233e629cfba6c081a846b558634233bf/oauth_dropins/indieauth.py#L207

2023-02-04 20:59 UTC, jamietanna commented
I'd literally just spotted that too :joy: